const ificationContent = [
  {
    title:"有声书",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"畅销书",
    content:[
      {text:"社科"},
      {text:"经管"},
      {text:"文学"},
      {text:"励志"},
      {text:"名著"},
      {text:"生活"}
    ]
  },
  {
    title:"儿童",
    content:[
      {text:"故事"},
      {text:"儿歌"},
      {text:"动画"},
      {text:"科普"},
      {text:"名著"},
      {text:"国学"}
    ]
  },
  {
    title:"相声评书",
    content:[
      {text:"单田芳"},
      {text:"郭德纲"},
      {text:"热门相声"},
      {text:"单口相声"},
      {text:"名家评书"},
      {text:"新锐笑将"}
    ]
  },
  {
    title:"情感生活",
    content:[
      {text:"恋爱技巧"},
      {text:"睡前夜话"},
      {text:"情绪压力"},
      {text:"婚姻家庭"},
      {text:"个人成长"},
      {text:"心理健康"}
    ]
  },
  {
    title:"人文",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"历史",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"国学书院",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"音乐",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"英语",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"教育培训",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"健康养生",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"广播剧",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
  {
    title:"戏曲",
    content:[
      {text:"言情"},
      {text:"悬疑"},
      {text:"都市"},
      {text:"幻想"},
      {text:"武侠"},
      {text:"历史"}
    ]
  },
]

module.exports = {
  ificationContent
}